# Components of a Time Series

A given time series can have four possible components:

1. Trend: denoted by $B_t$ captures the long run behavior of the time series of interest.

2. Season: denoted by $S_t$ are *periodic* fluctuations over *seasons*. The period of the season is fixed and known. For example, rise in non-durable sales during Christmas.

3. Cycle: denoted by $C_t$ are *non-periodic* fluctuations in that they occur regularly but over periods that are not fixed in duration.

4. Irregular: denoted by $\epsilon_t$ are random fluctuations, typically modeled as a white noise process.

## Decomposing a time series

We can decompose any given time series into its components. There are two ways to accomplish this:

1. Additive Decomposition: Here it is assumed that all four components are added to obtain the underlying time series:
\begin{equation}
y_t= B_t+S_t+C_t +\epsilon_t
\end{equation}

2. Multiplicative Decomposition: Here it is assumed that all four components are multiplied to obtain the underlying time series:
\begin{equation}
y_t= B_t \times S_t \times C_t \times \epsilon_t
\end{equation}

Note that using properties of logarithms, multiplicative decomposition is the same as additive decomposition in log terms:
\begin{equation}
log(y_t)= log(B_t) + log(S_t) + log(C_t) + log(\epsilon_t)
\end{equation}

Most statistical software can implement these decomposition using data on a time series variable as input. Typically they combine cyclical component with irregular component and provide a three-way decomposition. In Figure \@ref(fig:ch3-figure1) I use R to decompose real GDP for the US into its components.

```{r ch3-figure1, echo = FALSE, fig.cap = 'Additive Decomposition of Retail Sales', out.width='80%', fig.asp=.75, fig.align='center'}
suppressMessages(library(xts, warn.conflicts = FALSE, quietly=T))
suppressMessages(library(quantmod, warn.conflicts = FALSE, quietly = T))

# get data from fred stat
options("getSymbols.warning4.0"=FALSE)
invisible(getSymbols('RSXFSN',src='FRED'))

### function to convert xts
xts.to.ts <- function(X, freq = 12L) {
  ts(as.numeric(X), 
     start = c(.indexyear(X)[1] + 1900, .indexmon(X)[1] + 1),
     freq = freq)
}

#### get data

y1=xts.to.ts(log(RSXFSN))

#### additive decomposition

z=decompose(as.ts(y1),type="additive")
plot(cbind(observed = z$random + 
    z$trend + z$seasonal, trend = z$trend, seasonal = z$seasonal, 
        random = z$random), main = "") 

```


## Uses of Decomposition of a time series

The usefulness of decomposing a time series depends on our objective.

1. It may be of interest to study each component separately or to simply improve our understanding of the temporal dynamics of a time series of interest. Decomposing it into different components is the first step towards achieving that goal.

2. We can also use the decomposition to filter out components that we are not interested in studying. If for example we are only interested in modeling the cyclical component of the time series, then we can assume some kind decomposition, additive or multiplicative, and filter out the trend and seasonal component. For example, assuming additive decomposition, the filtered time series is given by:
\begin{equation}
Filtered \ y_t= y_t-B_t-S_t
\end{equation}

We can then proceed to model the cyclical component using the filtered data.