# Smoothing Methods 

One way to approach forecasting is to *average* out the fluctuations in the underlying time series to produce a *smoothed* data which can be extrapolated to produce forecasts. These smoothing methods are essentially *model-free* and may not even produce *optimal forecasts*. Depending on the method used one can accommodate seasonal as well as trend components of the underlying time series.
 

## Moving Average Method
 
We compute an average of most recent data values for the time series and use it as a forecast for the next period.

An important parameter is the *window* over which we take the average. Let us denote this window by $m$, then:
\begin{equation}
	y^f_{T+1}=\frac{\sum_{i=t-m+1}^{t}{y_i}}{m}
	\end{equation}
	
	
A larger value of $m$ produces greater smoothing and most software have a default value of this parameter which can be changed if needed.	
	
<!-- A larger value is more desirable when there are large but infrequent fluctuations in our data. In contrast, a smaller value of $m$ is preferred when data has sudden shits in our data. Typically, we set $m$ equal to the frequency at which our data is measured. For example, $m=4$ for quarterly data and $m=12$ for monthly data. One drawback of this method is that it assigns equal *weight* to each observation. It is reasonable to argue that for most economic and financial variables, the effect of past observations will be less pronounced than most recent observations.  -->
	

 
## Simple Exponential Smoothing

In the moving average method, all observations received same weight. However, it is reasonable to argue that more recent observations may have a greater influence than those in the remote past. In this method, the weight attached to past observations exponentially decay over time. Here is the algorithm for computing the smoothed data and its forecast:

1. Initialize at t=1: 
$$y_1^s=y_1$$

2. Update:
$$y_{t}^{s}= \alpha y_t + (1-\alpha)y_{t-1}^{s}  \quad for \ t=2,3,...T$$ 

3: h-period ahead forecast:
$$f_{T,h}= y_T^s$$
 
 Here the h-period ahead forecast is:

 
*Exercise: Can you show that 	$y_{t}^{s}$ is a is the weighted moving average of all past observations? Use backward substitution method.*

Here $\alpha \in (0,1)$ is the smoothing parameter, with smaller value indicating greater smoothing.


## Holt-Winters Smoothing

We add trend component to the simple exponential smoothing. In step 2 the equation we use to update the smoothed data is given by:

 \begin{align}
 	y_{t}^{s}= \alpha y_t + (1-\alpha)(y_{t-1}^{s}+B_{t-1})
 	B_t = \beta (y_t^s -y_{t-1}^s) + (1-\beta) B_{t-1}
 \end{align}
 
We now have an additional parameter $\beta$ that is the trend parameter. Here the h-period ahead forecast is:
  
  \begin{align}
  f_{T,h} = y_T^s + h\times B_T
  \end{align}
  
  

## Holt-Winters Smoothing with Seasonality
We now add seasonal component along with trend. Assuming multiplicative seasonality with period $n$:
 
  \begin{align}
  	y_{t}^{s}= \alpha \frac{y_t}{S_{t-n}} + (1-\alpha)(y_{t-1}^{s}+B_{t-1})\\
  	B_t = \gamma (y_t^s -y_{t-1}^s) + (1-\gamma) B_{t-1}\\
  	S_t = \beta\frac{y_t}{y_t^s}+(1-\beta)S_{t-n}
  \end{align}

The h-period ahead forecast is given by:
 
   \begin{equation}
   	f_{T,h}= (y_T^s + h\times B_T) \times S_{T+h-n}
   \end{equation}
   
## Application

We use R to implement a 12-period ahead forecast for retail sales for the U.S. The data is at monthly frequency from 1959 through 2015. We use natural logs of the data and compute smoothed series using each of the three methods. The resulting forecasts are plotted in Figure \@ref(fig:ch4-figure1).

```{r ch4-figure1, echo = FALSE, fig.cap = 'Forecast of Housing Starts: Three Smoothing Methods', out.width='80%', fig.asp=.75, fig.align='center'}
suppressMessages(library(forecast))
suppressMessages(library(timeSeries))

hstart=read.csv("/Users/home-mac/Documents/Econ-483-Notes/datafiles/hstarts.csv")
### create time series object
y=ts(hstart$y, start=c(2000,6), end=c(2018,6), frequency=12)

### simple exponential smoothing
s_exp1=HoltWinters(y,beta=FALSE, gamma=FALSE)
s_exp2=HoltWinters(y,beta=TRUE, gamma=FALSE)
s_exp3=HoltWinters(y,beta=TRUE, gamma=TRUE)


f_exp1=forecast(s_exp1,h=12)
f_exp2=forecast(s_exp2,h=12)
f_exp3=forecast(s_exp3,h=12)



par(mfrow=c(2,2))
par(mar=c(2,2,2,2))

plot(f_exp1, include=24, main="Simple Exponential Smoothing")
plot(f_exp2, include=24, main="Holt-Winters with Trend")
plot(f_exp3,include=24, main="Hold-Winters with Trend and Season")

```  